Invoking command in '/home/vedant/gaitlab_ws/OdriveCANControl/src/odrive_control_py': AMENT_PREFIX_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync:${AMENT_PREFIX_PATH} CMAKE_PREFIX_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync LD_LIBRARY_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can/lib:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync/lib:${LD_LIBRARY_PATH} PYTHONPATH=/home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/prefix_override:/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_control_py/lib/python3.10/site-packages:/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can/local/lib/python3.10/dist-packages:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync/local/lib/python3.10/dist-packages:${PYTHONPATH} /usr/bin/python3 -W ignore:setup.py install is deprecated setup.py egg_info --egg-base ../../build/odrive_control_py build --build-base /home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/build install --record /home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/install.log --single-version-externally-managed install_data
Invoked command in '/home/vedant/gaitlab_ws/OdriveCANControl/src/odrive_control_py' returned '0': AMENT_PREFIX_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync:${AMENT_PREFIX_PATH} CMAKE_PREFIX_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync LD_LIBRARY_PATH=/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can/lib:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync/lib:${LD_LIBRARY_PATH} PYTHONPATH=/home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/prefix_override:/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_control_py/lib/python3.10/site-packages:/home/vedant/gaitlab_ws/OdriveCANControl/install/odrive_can/local/lib/python3.10/dist-packages:/home/vedant/gaitlab_ws/OdriveCANControl/install/data_sync/local/lib/python3.10/dist-packages:${PYTHONPATH} /usr/bin/python3 -W ignore:setup.py install is deprecated setup.py egg_info --egg-base ../../build/odrive_control_py build --build-base /home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/build install --record /home/vedant/gaitlab_ws/OdriveCANControl/build/odrive_control_py/install.log --single-version-externally-managed install_data
